FROM python:3-alpine
RUN mkdir /simpleapp
WORKDIR /simpleapp
COPY requirements.txt /simpleapp
RUN pip install - upgrade pip
RUN pip install - no-cache-dir -r requirements.txt
COPY . /simpleapp
EXPOSE 5000
CMD [ "python", "myproject.py" ]